### PR TITLE
v4l2rtspserver: new recipe

### PR DESCRIPTION
**Pull request by mandraga**
Hi

This is a recipe for v4l2rtspserver, it streams video from a Video4linux device and sound from an Alsa device.
[https://github.com/mpromonet/v4l2rtspserver](url)
Last week, I worked with the maintainer to make it pass with a simple recipe. I tested it on a raspberry pi image:
[https://gitlab.com/arenyp/mipistreamer_yocto_rpi](url)

Best regards

### CODE REVIEW

**Review by kraj — CHANGES_REQUESTED** [review]
I see there was a release tagged

https://github.com/mpromonet/v4l2rtspserver/releases/tag/v0.3.3

In that case, I would suggest to rename recipe to `v4l2rtspserver_0.3.3.bb` and if you are building a SRCREV newer than that tag then add `PV .= "+0.3.4+git${SRCPV}"` in recipe to note that its somewhere inbetween 0.3.3 and 0.3.4

**Comment by mandraga** [comment]
Hi
Because it would not compile on the 0.3.3 release, I used ```PV .= "+0.3.4+git${SRCPV}"``` as you recommended. And tested it.

**Comment by kraj** [comment]
Generally you want to squash the commits into single commit here. I have done that locally in staging tree this time.

**Comment by kraj** [comment]
seeing failures with clang and libc++ runtime see failure on musl/qemuarm64 but its happening everywhere
https://errors.yoctoproject.org/Errors/Details/671994/

**Comment by mandraga** [comment]
> 

So if I push more commits on my fork, better to squash them?

**Comment by mandraga** [comment]
> seeing failures with clang and libc++ runtime see failure on musl/qemuarm64 but its happening everywhere https://errors.yoctoproject.org/Errors/Details/671994/

I added the clang layer to test this, but it is does not seem to be compiling my target. Reading the code, despite the warning, the way it is written guarantees that "m_rtcpInstance" is initialised.

**Comment by kraj** [comment]
> 

in you recipe add
```
TOOLCHAIN = "clang"
```

this will make it compile with clang.

**Comment by mandraga** [comment]
> > 
> 
> in you recipe add
> 
> ```
> TOOLCHAIN = "clang"
> ```
> 
> this will make it compile with clang.

It was doing nothing on the raspberry pi B+.

**Comment by mandraga** [comment]
I was silent for two weeks, but I will test it with clang on a x86 image and see if I can find a simple fix and make a pull request (otherwise it would be a patch).

**Comment by mpromonet** [comment]
Hi @mandraga,

I tagged a new release v0.3.6 that should avoid link to a non tagged version.

Best Regards,
Michel.

**Comment by mandraga** [comment]
Hi @mpromonet, thanks I am working with the 3.6 tag and I will soon make a pull request or something :)

**Comment by mpromonet** [comment]
Hi @mandraga 

I made a new release, that added an cmake option STATICSTDCPP=OFF to disable gcc static link, it was needed for integration in openwrt (see https://github.com/openwrt/packages/blob/master/multimedia/v4l2rtspserver/Makefile#L57).
It may be also interesting for openembedded depending how libc/libstdlib are managed.

Best Regards,
Michel.

**Comment by mandraga** [comment]
Cleaning the Clang compilation errors request took me already a day with no result. And honestly it disgusted me of completing that merge request. The meta Clang does not work on my target, then I had to target a PC and doing all this on my spare time on Sunday, it was too much for me. Maybe we should do like the gstreamer plugins project, make a the open embedded - the bad - the good and ugly, and put this recipe in the bad ones.

**Comment by kraj** [comment]
> Cleaning the Clang compilation errors request took me already a day with no result. And honestly it disgusted me of completing that merge request. The meta Clang does not work on my target, then I had to target a PC and doing all this on my spare time on Sunday, it was too much for me. Maybe we should do like the gstreamer plugins project, make a the open embedded - the bad - the good and ugly, and put this recipe in the bad ones.

if you update to latest as @mpromonet is suggesting and use cmake with option -DSTATICSTDCPP=OFF specified and upload new PR, I can schedule another CI run with clang and see how it goes.

**Comment by mandraga** [comment]
Updated to the latest release. Would you want to start from a new PR?

**Comment by kraj** [comment]
> Updated to the latest release. Would you want to start from a new PR?

I would prefer to keep using this PR as it has log trail. Please rebase your PR on top of latest master branch ( no merge ) and squash all your commits proposed here into single commit and push your PR branch to github.

**Comment by mandraga** [comment]
I do not see how to do this rebase neatly, I close the request.

**Comment by mandraga** [comment]
I do not see how to do this rebase neatly, I close the request.
